import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // TSX type for children prop
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="container mx-auto p-4">
          <h1 className="text-3xl font-bold mb-4">JSON Viewer</h1>
          <div className="flex">
            {/* Left box (smaller) */}
            <div className="flex-1 mr-2 bg-gray-200 p-4">
              <h2 className="text-xl font-semibold">Left Box</h2>
              {/* Content for left box */}
            </div>
            {/* Right box (larger) */}
            <div className="flex-2 bg-gray-300 p-4">
              <h2 className="text-xl font-semibold">Right Box</h2>
              {/* Content for right box */}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
